version: '3'
services:
  video-analytics:
    build: .
    ports:
     - "9600:9600"
    volumes:
     - .:/you_tube
    env_file:
     - api_keys.env
    expose:
     - "9600"
    dns:
     - 8.8.8.8
     - 9.9.9.9